version: '3.8'

services:
  flask-api:
    image: python:3.8-alpine
    ports:
      - 5000:5000
    depends_on:
      - historical-nba-database
    volumes:
      - ./:/api
    working_dir: /api
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DB: historical_nba_odds
    secrets:
      - mysql_password
    command: >
      sh -c 'pip install --upgrade pip &&
        apk add --no-cache build-base mariadb-dev &&
        adduser -D myuser &&
        chown -R myuser:myuser /api &&
        su myuser -c "pip install --user -r ./api/requirements.txt" &&
        su myuser -c "python -u ./api/app.py"
      '
  historical-nba-database:
    image: mysql:latest
    volumes:
      - orca-historical-nba-odds:/var/lib/mysql
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: historical_nba_odds
      MYSQL_TCP_PORT: 3307
    secrets:
      - mysql_root_password
volumes:
  orca-historical-nba-odds:
secrets:
  mysql_password:
    file: ./mysql_password.txt
  mysql_root_password:
    file: ./mysql_root_password.txt
#MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    